/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StwButton {
    }
    interface StwWelcome {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLStwButtonElement extends Components.StwButton, HTMLStencilElement {
    }
    var HTMLStwButtonElement: {
        prototype: HTMLStwButtonElement;
        new (): HTMLStwButtonElement;
    };
    interface HTMLStwWelcomeElement extends Components.StwWelcome, HTMLStencilElement {
    }
    var HTMLStwWelcomeElement: {
        prototype: HTMLStwWelcomeElement;
        new (): HTMLStwWelcomeElement;
    };
    interface HTMLElementTagNameMap {
        "stw-button": HTMLStwButtonElement;
        "stw-welcome": HTMLStwWelcomeElement;
    }
}
declare namespace LocalJSX {
    interface StwButton {
    }
    interface StwWelcome {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "stw-button": StwButton;
        "stw-welcome": StwWelcome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stw-button": LocalJSX.StwButton & JSXBase.HTMLAttributes<HTMLStwButtonElement>;
            "stw-welcome": LocalJSX.StwWelcome & JSXBase.HTMLAttributes<HTMLStwWelcomeElement>;
        }
    }
}
